---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kumadre-controller
  namespace: system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kumadre-controller
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["kumadre.controller"]
  resources: ["kumamonitors"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["kumadre.controller"]
  resources: ["kumamonitors/status"]
  verbs: ["get", "update", "patch"]
- apiGroups: ["kumadre.controller"]
  resources: ["kumaservers"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["kumadre.controller"]
  resources: ["kumaservers/status"]
  verbs: ["get", "update", "patch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["gateway.networking.k8s.io"]
  resources: ["httproutes", "tcproutes"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingressclasses"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["gateway.networking.k8s.io"]
  resources: ["gatewayclasses"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kumadre-controller
subjects:
- kind: ServiceAccount
  name: kumadre-controller
  namespace: system
roleRef:
  kind: ClusterRole
  name: kumadre-controller
  apiGroup: rbac.authorization.k8s.io
