//go:build !ignore_autogenerated
// +build !ignore_autogenerated

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *KumaMonitor) DeepCopyObject() runtime.Object {
	return in.DeepCopy()
}

func (in *KumaMonitorList) DeepCopyObject() runtime.Object {
	return in.DeepCopy()
}

func (in *KumaMonitor) DeepCopy() *KumaMonitor {
	if in == nil {
		return nil
	}
	out := new(KumaMonitor)
	in.DeepCopyInto(out)
	return out
}

func (in *KumaMonitor) DeepCopyInto(out *KumaMonitor) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *KumaMonitorSpec) DeepCopyInto(out *KumaMonitorSpec) {
	*out = *in
	if in.WatchResources != nil {
		in, out := &in.WatchResources, &out.WatchResources
		*out = make([]ResourceKind, len(*in))
		copy(*out, *in)
	}
}

func (in *KumaMonitorSpec) DeepCopy() *KumaMonitorSpec {
	if in == nil {
		return nil
	}
	out := new(KumaMonitorSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *KumaMonitorStatus) DeepCopyInto(out *KumaMonitorStatus) {
	*out = *in
	if in.Monitors != nil {
		in, out := &in.Monitors, &out.Monitors
		*out = make([]MonitorInfo, len(*in))
		copy(*out, *in)
	}
}

func (in *KumaMonitorStatus) DeepCopy() *KumaMonitorStatus {
	if in == nil {
		return nil
	}
	out := new(KumaMonitorStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *KumaMonitorList) DeepCopy() *KumaMonitorList {
	if in == nil {
		return nil
	}
	out := new(KumaMonitorList)
	in.DeepCopyInto(out)
	return out
}

func (in *KumaMonitorList) DeepCopyInto(out *KumaMonitorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KumaMonitor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *KumaServer) DeepCopyObject() runtime.Object {
	return in.DeepCopy()
}

func (in *KumaServerList) DeepCopyObject() runtime.Object {
	return in.DeepCopy()
}

func (in *KumaServer) DeepCopy() *KumaServer {
	if in == nil {
		return nil
	}
	out := new(KumaServer)
	in.DeepCopyInto(out)
	return out
}

func (in *KumaServer) DeepCopyInto(out *KumaServer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

func (in *KumaServerList) DeepCopy() *KumaServerList {
	if in == nil {
		return nil
	}
	out := new(KumaServerList)
	in.DeepCopyInto(out)
	return out
}

func (in *KumaServerList) DeepCopyInto(out *KumaServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KumaServer, len(*in))
		copy(*out, *in)
	}
}
